codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 70%
        threshold: 1%
        base: auto
        flags:
          - unittests
        paths:
          - "jaxace/"
    patch:
      default:
        target: 70%
        threshold: 1%
        base: auto

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "**/__pycache__/**/*"
  - "**/*.pyc"
  - "setup.py"
  - "**/__init__.py"
  - "**/test_*.py"

flags:
  unittests:
    paths:
      - jaxace/
    carryforward: true