"""Tests for reusable spline objects and fixed-grid spline plans."""

from pathlib import Path

import jax
import jax.numpy as jnp
import numpy as np
import pytest
import jaxace
from importlib.metadata import version

from jaxace import (
    AkimaSpline,
    AkimaSplinePlan,
    CubicSpline,
    CubicSplinePlan,
    CubicBSpline,
    CubicBSplinePlan,
    akima_interpolation,
    cubic_spline_interpolation,
    cubic_b_spline_interpolation,
    evaluate_akima_spline,
    evaluate_cubic_spline,
    prepare_akima_spline,
    prepare_akima_spline_plan,
    prepare_cubic_spline,
    prepare_cubic_spline_plan,
    prepare_cubic_b_spline_plan,
)

jax.config.update("jax_enable_x64", True)

DATA_DIR = Path(__file__).parent / "data"


@pytest.fixture(scope="module")
def julia_reference():
    """Load outputs generated by AbstractCosmologicalEmulators.jl."""
    inputs = np.loadtxt(DATA_DIR / "spline_reference_inputs.txt")
    outputs = np.loadtxt(DATA_DIR / "spline_reference_outputs.txt")
    return {
        "t": jnp.asarray(inputs[:, 0]),
        "u1": jnp.asarray(inputs[:, 1]),
        "u2": jnp.asarray(inputs[:, 2]),
        "t_new": jnp.asarray(outputs[:, 0]),
        "akima_u1": outputs[:, 1],
        "akima_u2": outputs[:, 2],
        "cubic_u1": outputs[:, 3],
        "cubic_u2": outputs[:, 4],
        "bspline_u1": outputs[:, 5],
        "bspline_u2": outputs[:, 6],
    }


def test_pure_functions_match_julia_reference(julia_reference):
    """Keep the JAX kernels tied to saved Julia reference outputs."""
    ref = julia_reference
    np.testing.assert_allclose(
        akima_interpolation(ref["u1"], ref["t"], ref["t_new"]),
        ref["akima_u1"],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        cubic_spline_interpolation(ref["u1"], ref["t"], ref["t_new"]),
        ref["cubic_u1"],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        cubic_b_spline_interpolation(ref["u1"], ref["t"], ref["t_new"]),
        ref["bspline_u1"],
        rtol=1e-12,
        atol=1e-12,
    )


def test_fixed_value_spline_objects(julia_reference):
    """Prepared Akima and cubic splines reuse coefficients across query grids."""
    ref = julia_reference
    akima = prepare_akima_spline(ref["u1"], ref["t"])
    cubic = CubicSpline(ref["u1"], ref["t"])
    cubic_from_helper = prepare_cubic_spline(ref["u1"], ref["t"])

    np.testing.assert_allclose(
        evaluate_akima_spline(akima, ref["t_new"]),
        ref["akima_u1"],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        evaluate_cubic_spline(cubic, ref["t_new"]),
        ref["cubic_u1"],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        cubic_from_helper(ref["t_new"]),
        ref["cubic_u1"],
        rtol=1e-12,
        atol=1e-12,
    )

    other_query = jnp.array([0.0, 0.07, 0.9, 2.7, 5.0])
    np.testing.assert_allclose(
        cubic(other_query),
        cubic_spline_interpolation(ref["u1"], ref["t"], other_query),
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(cubic(ref["t"]), ref["u1"], atol=1e-12)


def test_cubic_spline_matrix_jit_and_gradient(julia_reference):
    """The fixed-value cubic object supports matrices, JIT, and query AD."""
    ref = julia_reference
    values = jnp.column_stack((ref["u1"], ref["u2"]))
    spline = CubicSpline(values, ref["t"])
    expected = cubic_spline_interpolation(values, ref["t"], ref["t_new"])

    compiled = jax.jit(lambda query: spline(query))
    result = compiled(ref["t_new"])
    result.block_until_ready()
    np.testing.assert_allclose(result, expected, rtol=1e-12, atol=1e-12)

    query = jnp.linspace(0.05, 4.95, 31)
    object_grad = jax.grad(lambda q: jnp.sum(spline(q)))(query)
    pure_grad = jax.grad(
        lambda q: jnp.sum(cubic_spline_interpolation(values, ref["t"], q))
    )(query)
    np.testing.assert_allclose(object_grad, pure_grad, rtol=1e-11, atol=1e-11)


@pytest.mark.parametrize(
    ("plan_type", "prepare_plan", "interpolation", "reference_keys"),
    (
        (
            AkimaSplinePlan,
            prepare_akima_spline_plan,
            akima_interpolation,
            ("akima_u1", "akima_u2"),
        ),
        (
            CubicSplinePlan,
            prepare_cubic_spline_plan,
            cubic_spline_interpolation,
            ("cubic_u1", "cubic_u2"),
        ),
        (
            CubicBSplinePlan,
            prepare_cubic_b_spline_plan,
            cubic_b_spline_interpolation,
            ("bspline_u1", "bspline_u2"),
        ),
    ),
)
def test_fixed_grid_plans_match_julia_and_accept_changing_values(
    julia_reference,
    plan_type,
    prepare_plan,
    interpolation,
    reference_keys,
):
    """One plan must handle changing vectors and matrices without rebuilding."""
    ref = julia_reference
    plan = plan_type(ref["t"], ref["t_new"])
    helper_plan = prepare_plan(ref["t"], ref["t_new"])

    result1 = plan(ref["u1"])
    result2 = plan(ref["u2"])
    np.testing.assert_allclose(
        result1,
        ref[reference_keys[0]],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        result2,
        ref[reference_keys[1]],
        rtol=1e-12,
        atol=1e-12,
    )
    np.testing.assert_allclose(
        helper_plan(ref["u1"]),
        result1,
        rtol=1e-12,
        atol=1e-12,
    )
    assert not np.allclose(result1, result2)

    values = jnp.column_stack((ref["u1"], ref["u2"]))
    matrix_result = plan(values)
    matrix_expected = interpolation(values, ref["t"], ref["t_new"])
    assert matrix_result.shape == (len(ref["t_new"]), 2)
    np.testing.assert_allclose(
        matrix_result,
        matrix_expected,
        rtol=1e-12,
        atol=1e-12,
    )


@pytest.mark.parametrize(
    ("plan_type", "interpolation"),
    (
        (AkimaSplinePlan, akima_interpolation),
        (CubicSplinePlan, cubic_spline_interpolation),
        (CubicBSplinePlan, cubic_b_spline_interpolation),
    ),
)
def test_fixed_grid_plans_jit_dynamic_values_and_reverse_grad(
    julia_reference,
    plan_type,
    interpolation,
):
    """Compiled plans keep ``u`` dynamic and preserve reverse-mode gradients."""
    ref = julia_reference
    plan = plan_type(ref["t"], ref["t_new"])
    compiled = jax.jit(plan)

    result1 = compiled(ref["u1"])
    result2 = compiled(ref["u2"])
    result1.block_until_ready()
    result2.block_until_ready()

    np.testing.assert_allclose(result1, plan(ref["u1"]), rtol=1e-12, atol=1e-12)
    np.testing.assert_allclose(result2, plan(ref["u2"]), rtol=1e-12, atol=1e-12)
    assert not np.allclose(result1, result2)

    def plan_loss(values):
        return jnp.sum(plan(values))

    def pure_loss(values):
        return jnp.sum(interpolation(values, ref["t"], ref["t_new"]))
    plan_grad = jax.jit(jax.grad(plan_loss))(ref["u1"])
    pure_grad = jax.grad(pure_loss)(ref["u1"])
    plan_grad.block_until_ready()
    np.testing.assert_allclose(plan_grad, pure_grad, rtol=1e-10, atol=1e-10)
    assert jnp.all(jnp.isfinite(plan_grad))


def test_spline_dataclasses_are_jax_pytrees(julia_reference):
    """CubicSpline and both plans can cross a JIT boundary as arguments."""
    ref = julia_reference
    objects = (
        CubicSpline(ref["u1"], ref["t"]),
        AkimaSplinePlan(ref["t"], ref["t_new"]),
        CubicSplinePlan(ref["t"], ref["t_new"]),
        CubicBSpline(ref["u1"], ref["t"]),
        CubicBSplinePlan(ref["t"], ref["t_new"]),
    )
    for obj in objects:
        leaves = jax.tree_util.tree_leaves(obj)
        assert leaves
        assert all(isinstance(leaf, jax.Array) for leaf in leaves)

    evaluate_plan = jax.jit(lambda plan, values: plan(values))
    result = evaluate_plan(objects[2], ref["u1"])
    result.block_until_ready()
    np.testing.assert_allclose(result, ref["cubic_u1"], rtol=1e-12, atol=1e-12)


def test_akima_spline_has_the_same_constructor_as_cubic(julia_reference):
    ref = julia_reference
    spline = AkimaSpline(ref["u1"], ref["t"])
    result = jax.jit(spline)(ref["t_new"])
    result.block_until_ready()
    np.testing.assert_allclose(result, ref["akima_u1"], rtol=1e-12, atol=1e-12)


def test_runtime_version_matches_package_metadata():
    assert jaxace.__version__ == version("jaxace")
