"""Generate the Julia reference fixture consumed by the jaxace tests.

Run from the jaxace repository with:

    julia --project=../AbstractCosmologicalEmulators.jl \
        scripts/generate_spline_reference.jl

The fixture records Float64 outputs from the pure ACE interpolation functions.
The source package commit is included in the file header so regeneration is
auditable. The JAX tests then provide a separate cross-language parity check.
"""

using AbstractCosmologicalEmulators
using DelimitedFiles

const ROOT = normpath(joinpath(@__DIR__, ".."))
const DATA_DIR = joinpath(ROOT, "tests", "data")
const ACE_ROOT = normpath(joinpath(ROOT, "..", "AbstractCosmologicalEmulators.jl"))

const t = Float64[0.0, 0.03, 0.2, 0.75, 1.4, 2.0, 3.5, 5.0]
const t_new = collect(range(0.0, 5.0; length=101))
const u1 = @. sin(1.3 * t) + 0.2 * cos(2.1 * t)
const u2 = @. 0.7 * cos(0.8 * t) - 0.15 * sin(1.7 * t) + 0.03 * t

function source_commit()
    try
        return readchomp(`git -C $ACE_ROOT rev-parse HEAD`)
    catch
        return "unknown"
    end
end

function write_with_header(path, header, values)
    open(path, "w") do io
        for line in header
            println(io, "# ", line)
        end
        writedlm(io, values, '\t')
    end
end

mkpath(DATA_DIR)
commit = source_commit()
inputs = hcat(t, u1, u2)
outputs = hcat(
    t_new,
    AbstractCosmologicalEmulators.akima_interpolation(u1, t, t_new),
    AbstractCosmologicalEmulators.akima_interpolation(u2, t, t_new),
    AbstractCosmologicalEmulators.cubic_spline_interpolation(u1, t, t_new),
    AbstractCosmologicalEmulators.cubic_spline_interpolation(u2, t, t_new),
)

write_with_header(
    joinpath(DATA_DIR, "spline_reference_inputs.txt"),
    [
        "Generated by AbstractCosmologicalEmulators.jl",
        "Source ACE commit: $commit",
        "Float type: Float64",
        "u1(t) = sin(1.3t) + 0.2cos(2.1t)",
        "u2(t) = 0.7cos(0.8t) - 0.15sin(1.7t) + 0.03t",
        "columns: t u1 u2; t is nonuniform",
    ],
    inputs,
)
write_with_header(
    joinpath(DATA_DIR, "spline_reference_outputs.txt"),
    [
        "Generated by AbstractCosmologicalEmulators.jl",
        "Source ACE commit: $commit; Float64 pure interpolation functions",
        "columns: t_new akima_u1 akima_u2 cubic_u1 cubic_u2",
        "t_new = range(0, 5, length=101); no extrapolation",
    ],
    outputs,
)

println("Wrote spline reference fixtures using ACE commit $commit")
